# Working directory is where intermediate files are placed. If running
# packet2 vec on different datasets, make sure the working directory
# is unique for each.
working: /Code/p2v_test_data/output
train_data: /Code/p2v_test_data/raw_pcaps_train
test_data: /Code/p2v_test_data/raw_pcaps_test
darpa: /Code/data/DARPA2009_groundtruth.csv
options:
  threads: 10
hyperparameters:
  ngram: 2
  vocab_size: 50000
classifiers:
  - rfc
  - gnb
